"""Winding/monodromy state on pulled multivariate branch divisors."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

import sympy as sp

from .coverage import CoverageCertificate


@dataclass(frozen=True)
class WindingState:
    divisor_index: int
    winding: sp.Expr = sp.S.Zero
    argument_increment: sp.Expr = sp.S.Zero
    log_increment: sp.Expr = sp.S.Zero
    multiplier: sp.Expr = sp.S.One
    certified: bool = True

    @classmethod
    def turns(cls, index, n=1, power=None):
        n = sp.sympify(n)
        delta = 2 * sp.pi * n
        mult = (
            sp.S.One
            if power is None
            else sp.exp(2 * sp.pi * sp.I * n * sp.sympify(power))
        )
        return cls(index, n, delta, 2 * sp.pi * sp.I * n, sp.simplify(mult), True)


@dataclass(frozen=True)
class MonodromyState:
    windings: tuple[WindingState, ...] = ()
    coverage: CoverageCertificate | None = None

    def winding_for(self, index):
        for w in self.windings:
            if w.divisor_index == index:
                return w
        return WindingState(index)

    def compose(self, other):
        by = {}
        for w in self.windings + other.windings:
            old = by.get(w.divisor_index, WindingState(w.divisor_index))
            by[w.divisor_index] = WindingState(
                w.divisor_index,
                sp.simplify(old.winding + w.winding),
                sp.simplify(old.argument_increment + w.argument_increment),
                sp.simplify(old.log_increment + w.log_increment),
                sp.simplify(old.multiplier * w.multiplier),
                old.certified and w.certified,
            )
        return MonodromyState(
            tuple(by[k] for k in sorted(by)), self.coverage or other.coverage
        )


def propagate_monodromy(expr, divisors, state):
    """Apply pulled-divisor winding to nested principal log/power operations."""
    expr = sp.sympify(expr)
    index = {d.operation: i for i, d in enumerate(divisors)}

    def rec(node):
        args = tuple(rec(a) for a in node.args)
        rebuilt = node.func(*args) if args else node
        i = index.get(node)
        if i is None:
            return rebuilt
        w = state.winding_for(i)
        if node.func is sp.log:
            return sp.expand(rebuilt + w.log_increment)
        if node.func is sp.arg:
            return sp.expand(rebuilt + w.argument_increment)
        if node.is_Pow and node.exp.is_integer is not True:
            return sp.expand(rebuilt * w.multiplier)
        return rebuilt

    return rec(expr)


def monodromy_cluster(expr, divisors, *, turn_symbol=None):
    """Symbolic repeated-winding family. Finite only when dependence cancels."""
    n = turn_symbol or sp.Symbol("_winding", integer=True)
    state = MonodromyState(
        tuple(
            WindingState.turns(i, n, d.operation.exp if d.kind == "power" else None)
            for i, d in enumerate(divisors)
        )
    )
    family = sp.simplify(propagate_monodromy(expr, divisors, state))
    finite = n not in family.free_symbols
    return family, finite, state


class ExtendedClusterKind(str, Enum):
    FINITE_CYCLIC = "finite_cyclic"
    INFINITE_DISCRETE = "infinite_discrete"
    DENSE_PHASE = "dense_phase"
    DIVERGENT = "divergent"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class ExtendedComplexCluster:
    kind: ExtendedClusterKind
    representation: sp.Expr | sp.Set | None
    generator: sp.Expr | None
    period: int | None
    coverage: CoverageCertificate
    statement: str


def classify_monodromy_cluster(expr, divisors, *, branch_point=False):
    """Classify the orbit generated by one positive turn around all divisors."""
    expr = sp.sympify(expr)
    n = sp.Symbol("_winding", integer=True)
    family, finite, _state = monodromy_cluster(expr, divisors, turn_symbol=n)
    if finite:
        return ExtendedComplexCluster(
            ExtendedClusterKind.FINITE_CYCLIC,
            sp.FiniteSet(family),
            sp.S.One,
            1,
            CoverageCertificate.complete(
                "monodromy_cluster", "winding cancels", (family,)
            ),
            "monodromy is trivial after simplification",
        )
    # additive logarithmic translate a + n*c
    c = sp.simplify(family.subs(n, n + 1) - family)
    if n not in c.free_symbols and c != 0:
        if branch_point and sp.re(c) == 0 and sp.im(c) != 0:
            return ExtendedComplexCluster(
                ExtendedClusterKind.INFINITE_DISCRETE,
                sp.ImageSet(sp.Lambda(n, family), sp.S.Integers),
                c,
                None,
                CoverageCertificate.complete(
                    "logarithmic_monodromy",
                    "constant nonzero logarithmic translation",
                    (c,),
                ),
                "repeated winding gives an infinite discrete logarithmic translate",
            )
        return ExtendedComplexCluster(
            ExtendedClusterKind.INFINITE_DISCRETE,
            sp.ImageSet(sp.Lambda(n, family), sp.S.Integers),
            c,
            None,
            CoverageCertificate.complete(
                "additive_monodromy", "constant nonzero additive translation", (c,)
            ),
            "repeated winding gives an infinite discrete translate",
        )
    # multiplicative orbit q**n * a
    f0 = sp.simplify(family.subs(n, 0))
    f1 = sp.simplify(family.subs(n, 1))
    if f0 != 0:
        q = sp.simplify(f1 / f0)
        if n not in q.free_symbols:
            root_unity = False
            period = None
            for candidate_period in range(1, 25):
                if sp.simplify(q**candidate_period - 1) == 0:
                    root_unity = True
                    period = candidate_period
                    break
            powers = [d.operation.exp for d in divisors if d.kind == "power"]
            if not root_unity and powers and all(a.is_Rational for a in powers):
                from math import lcm

                period = lcm(*(int(a.q) for a in powers))
                root_unity = True
            if root_unity:
                return ExtendedComplexCluster(
                    ExtendedClusterKind.FINITE_CYCLIC,
                    sp.ImageSet(sp.Lambda(n, family), sp.S.Integers),
                    q,
                    period,
                    CoverageCertificate.complete(
                        "finite_monodromy", "root-of-unity multiplier", (q,)
                    ),
                    "monodromy multiplier has certified finite order",
                )
            irrational_real_power = any(
                a.is_real is True and a.is_irrational is True for a in powers
            )
            if irrational_real_power and sp.simplify(sp.Abs(q) - 1) == 0:
                return ExtendedComplexCluster(
                    ExtendedClusterKind.DENSE_PHASE,
                    sp.ImageSet(sp.Lambda(n, family), sp.S.Integers),
                    q,
                    None,
                    CoverageCertificate.complete(
                        "phase_monodromy",
                        "certified irrational unit-modulus rotation",
                        (q,),
                    ),
                    "monodromy generates a dense phase orbit from a certified irrational rotation",
                )
            if branch_point and (sp.Abs(q).is_zero is False):
                return ExtendedComplexCluster(
                    ExtendedClusterKind.DIVERGENT,
                    sp.ImageSet(sp.Lambda(n, family), sp.S.Integers),
                    q,
                    None,
                    CoverageCertificate.complete(
                        "divergent_monodromy",
                        "non-unit multiplier at branch point",
                        (q,),
                    ),
                    "winding orbit is unbounded in at least one direction",
                )
    return ExtendedComplexCluster(
        ExtendedClusterKind.UNKNOWN,
        family,
        None,
        None,
        CoverageCertificate.unknown(
            "monodromy_cluster", "orbit type could not be certified"
        ),
        "symbolic winding family remains unclassified",
    )


__all__ = [
    "ExtendedClusterKind",
    "ExtendedComplexCluster",
    "MonodromyState",
    "WindingState",
    "classify_monodromy_cluster",
    "monodromy_cluster",
    "propagate_monodromy",
]
