from __future__ import annotations

import heapq
from collections import Counter
from collections.abc import Callable, Iterable
from dataclasses import dataclass, field
from enum import Enum
from itertools import count

import sympy as sp

from ._ordering import exponent_sort_key as exponent_key
from ._power_simplify import analytic_powsimp
from .context import AsymptoticContext
from .obligations import (
    AsymptoticKnowledge,
    AsymptoticObligation,
    DepthLimitObligation,
    ExponentialScaleObligation,
    LogarithmicScaleObligation,
    NonAnalyticObligation,
    UnsupportedNodeObligation,
    ZeroTestObligation,
)


@dataclass(frozen=True)
class LazyTerm:
    exponent: sp.Expr
    coefficient: sp.Expr


_ANALYTIC_UNARY_FUNCS = {
    sp.sin,
    sp.cos,
    sp.tan,
    sp.sinh,
    sp.cosh,
    sp.tanh,
    sp.asin,
    sp.acos,
    sp.atan,
    sp.erf,
}


class ContinuationStatus(str, Enum):
    READY = "ready"
    RUNNING = "running"
    SUSPENDED = "suspended"
    DONE = "done"


@dataclass
class SparseNodeState:
    """Persistent continuation state for one expression-tree node.

    ``result`` is the already emitted nonzero term prefix.  Stateful merge,
    product and analytic-composition frontiers live in ``payload`` and retain
    their exact heap/cursor state across both larger requests and obligation
    suspension/resumption.
    """

    expr: sp.Expr
    status: ContinuationStatus = ContinuationStatus.READY
    requested: int = 0
    result: tuple[LazyTerm, ...] = ()
    obligation: AsymptoticObligation | None = None
    payload: dict[str, object] = field(default_factory=dict)
    evaluations: int = 0
    resumptions: int = 0
    exhausted: bool = False


@dataclass
class SparseContinuation:
    series: LazySparseSeries
    requested: int
    result: tuple[LazyTerm, ...] | None = None
    obligation: AsymptoticObligation | None = None
    done: bool = False
    resumes: int = 0

    def run(self) -> list[LazyTerm] | None:
        value = self.series.terms(self.requested)
        if value is None:
            self.result = None
            self.obligation = self.series.obligation
            self.done = False
            return None
        self.result = tuple(value)
        self.obligation = None
        self.done = True
        return value

    def resume(self, obligation: AsymptoticObligation | None = None) -> list[LazyTerm] | None:
        self.series.resume(obligation or self.obligation)
        self.resumes += 1
        return self.run()


@dataclass
class SparseTermStream:
    """Public demand-driven view of a sparse node.

    ``next_term`` asks for exactly one additional surviving term.  No guessed
    prefix multiplier or refinement bound is involved; if cancellation removes
    a candidate the underlying frontier simply advances again.
    """

    series: LazySparseSeries
    expr: sp.Expr
    depth: int = 0
    index: int = 0

    def next_term(self) -> LazyTerm | None:
        terms = self.series._eval(self.expr, self.index + 1, self.depth)
        if terms is None:
            return None
        if len(terms) <= self.index:
            return None
        term = terms[self.index]
        self.index += 1
        return term

    @property
    def exhausted(self) -> bool:
        return self.series._state(self.expr).exhausted


def combine_terms(terms: Iterable[LazyTerm], n: int | None = None) -> list[LazyTerm]:
    grouped = {}
    for term in terms:
        exponent = sp.simplify(term.exponent)
        grouped[exponent] = grouped.get(exponent, sp.S.Zero) + term.coefficient
    result = [
        LazyTerm(exp, analytic_powsimp(coeff))
        for exp, coeff in grouped.items()
        if analytic_powsimp(coeff) != 0
    ]
    result.sort(key=lambda term: exponent_key(term.exponent))
    return result if n is None else result[:n]


def multiply_lists(a: list[LazyTerm], b: list[LazyTerm], n: int) -> list[LazyTerm]:
    """Compatibility helper for finite lists.

    Internal sparse evaluation no longer uses this truncating helper; products
    are generated by a persistent best-first frontier over child streams.
    """
    products = [
        LazyTerm(sp.simplify(x.exponent + y.exponent), x.coefficient * y.coefficient)
        for x in a
        for y in b
    ]
    return combine_terms(products, n)


class _Suspend(Exception):
    pass


class _NodeSource:
    def __init__(self, owner: LazySparseSeries, expr: sp.Expr, depth: int) -> None:
        self.owner = owner
        self.expr = expr
        self.depth = depth

    def get(self, index: int) -> LazyTerm | None:
        value = self.owner._eval(self.expr, index + 1, self.depth)
        if value is None:
            raise _Suspend
        if index < len(value):
            return value[index]
        return None

    @property
    def exhausted(self) -> bool:
        return self.owner._state(self.expr).exhausted


class _MappedSource:
    def __init__(
        self, source: _NodeSource, mapper: Callable[[LazyTerm], LazyTerm | None], offset: int = 0
    ) -> None:
        self.source = source
        self.mapper = mapper
        self.offset = offset
        self.cache: list[LazyTerm] = []
        self.raw_index = offset
        self._exhausted = False

    def get(self, index: int) -> LazyTerm | None:
        while len(self.cache) <= index and not self._exhausted:
            term = self.source.get(self.raw_index)
            if term is None:
                if self.source.exhausted:
                    self._exhausted = True
                return None
            self.raw_index += 1
            mapped = self.mapper(term)
            if mapped is not None:
                self.cache.append(mapped)
        return self.cache[index] if index < len(self.cache) else None

    @property
    def exhausted(self) -> bool:
        return self._exhausted


class _PersistentAddFrontier:
    def __init__(
        self, owner: LazySparseSeries, args: tuple[sp.Expr, ...], depth: int, node: sp.Expr
    ) -> None:
        self.owner = owner
        self.node = node
        self.sources = [_NodeSource(owner, arg, depth) for arg in args]
        self.indices = [0] * len(args)
        self.heap: list[tuple[tuple[object, ...], int, int, LazyTerm]] = []
        self.ticket = count()
        self.output: list[LazyTerm] = []
        self.initialized = False
        self.init_index = 0
        self.exhausted = False
        self.pending: tuple[sp.Expr, sp.Expr, list[int], int] | None = None

    def _push_child(self, i: int) -> None:
        term = self.sources[i].get(self.indices[i])
        if term is None:
            return
        heapq.heappush(self.heap, (exponent_key(term.exponent), next(self.ticket), i, term))

    def _initialize(self) -> None:
        if self.initialized:
            return
        while self.init_index < len(self.sources):
            self._push_child(self.init_index)
            self.init_index += 1
        self.initialized = True
        self._update_exhausted()

    def _update_exhausted(self) -> None:
        self.exhausted = not self.heap and all(src.exhausted for src in self.sources)

    def terms_up_to(self, n: int) -> list[LazyTerm]:
        self._initialize()
        while len(self.output) < n and (self.heap or self.pending is not None):
            if self.pending is None:
                _, _, i, first = heapq.heappop(self.heap)
                exponent = first.exponent
                coefficient = first.coefficient
                consumed = [i]
                while self.heap:
                    _, _, j, term = self.heap[0]
                    if sp.simplify(term.exponent - exponent) != 0:
                        break
                    heapq.heappop(self.heap)
                    coefficient += term.coefficient
                    consumed.append(j)
                self.pending = (exponent, coefficient, consumed, 0)
            exponent, coefficient, consumed, progress = self.pending
            zero = coefficient == 0
            if len(consumed) > 1 and not zero and self.owner._potential_cancellation(coefficient):
                zero = self.owner._zero_or_suspend(
                    coefficient,
                    self.node,
                    "addition must decide cancellation of equal-exponent coefficients",
                )
            while progress < len(consumed):
                j = consumed[progress]
                target = self.indices[j] + 1
                term = self.sources[j].get(target)
                self.indices[j] = target
                if term is not None:
                    heapq.heappush(
                        self.heap, (exponent_key(term.exponent), next(self.ticket), j, term)
                    )
                progress += 1
                self.pending = (exponent, coefficient, consumed, progress)
            if not zero:
                self.output.append(LazyTerm(sp.simplify(exponent), analytic_powsimp(coefficient)))
            self.pending = None
            self._update_exhausted()
        return self.output[:n]


class _PersistentProductFrontier:
    """Best-first Cartesian product over two *streams*, not finite prefixes."""

    def __init__(self, owner: LazySparseSeries, left, right, node: sp.Expr) -> None:
        self.owner = owner
        self.left = left
        self.right = right
        self.node = node
        self.heap: list[tuple[tuple[object, ...], int, int, int, sp.Expr]] = []
        self.seen: set[tuple[int, int]] = set()
        self.ticket = count()
        self.output: list[LazyTerm] = []
        self.initialized = False
        self.exhausted = False
        self.pending: tuple[sp.Expr, sp.Expr, list[tuple[int, int]]] | None = None

    def _get_pair(self, i: int, j: int):
        a = self.left.get(i)
        b = self.right.get(j)
        if a is None or b is None:
            return None
        return a, b

    def _push(self, i: int, j: int) -> None:
        if (i, j) in self.seen:
            return
        pair = self._get_pair(i, j)
        if pair is None:
            return
        self.seen.add((i, j))
        a, b = pair
        exponent = sp.simplify(a.exponent + b.exponent)
        heapq.heappush(self.heap, (exponent_key(exponent), next(self.ticket), i, j, exponent))

    def _initialize(self) -> None:
        if not self.initialized:
            self._push(0, 0)
            self.initialized = True
            self._update_exhausted()

    def _update_exhausted(self) -> None:
        self.exhausted = not self.heap and (self.left.exhausted or self.right.exhausted)

    def terms_up_to(self, n: int) -> list[LazyTerm]:
        self._initialize()
        while len(self.output) < n and (self.heap or self.pending is not None):
            if self.pending is None:
                _, _, i, j, exponent = heapq.heappop(self.heap)
                pairs = [(i, j)]
                a, b = self._get_pair(i, j)
                coefficient = a.coefficient * b.coefficient
                while self.heap:
                    _, _, ii, jj, e2 = self.heap[0]
                    if sp.simplify(e2 - exponent) != 0:
                        break
                    heapq.heappop(self.heap)
                    a, b = self._get_pair(ii, jj)
                    coefficient += a.coefficient * b.coefficient
                    pairs.append((ii, jj))
                self.pending = (exponent, coefficient, pairs)
            exponent, coefficient, pairs = self.pending
            zero = coefficient == 0
            if len(pairs) > 1 and not zero and self.owner._potential_cancellation(coefficient):
                zero = self.owner._zero_or_suspend(
                    coefficient,
                    self.node,
                    "product must decide cancellation of equal-exponent contributions",
                )
            for ii, jj in pairs:
                self._push(ii + 1, jj)
                self._push(ii, jj + 1)
            if not zero:
                self.output.append(LazyTerm(exponent, analytic_powsimp(coefficient)))
            self.pending = None
            self._update_exhausted()
        return self.output[:n]


class _ProductSource:
    def __init__(self, frontier: _PersistentProductFrontier) -> None:
        self.frontier = frontier

    def get(self, index: int) -> LazyTerm | None:
        out = self.frontier.terms_up_to(index + 1)
        return out[index] if index < len(out) else None

    @property
    def exhausted(self) -> bool:
        return self.frontier.exhausted


class _DynamicAnalyticFrontier:
    """Best-first Taylor tuple frontier backed by a demand-driven tail stream."""

    def __init__(
        self, owner: LazySparseSeries, tail, taylor: Callable[[int], sp.Expr], node: sp.Expr
    ) -> None:
        self.owner = owner
        self.tail = tail
        self.taylor = taylor
        self.node = node
        self.heap: list[tuple[tuple[object, ...], int, tuple[int, ...], sp.Expr]] = []
        self.seen: set[tuple[int, ...]] = set()
        self.ticket = count()
        self.output: list[LazyTerm] = []
        self.initialized = False
        self.exhausted = False
        self.pending: tuple[sp.Expr, sp.Expr, list[tuple[int, ...]]] | None = None

    def _weight(self, indices: tuple[int, ...]) -> sp.Expr | None:
        vals = [self.tail.get(i) for i in indices]
        if any(v is None for v in vals):
            return None
        return sp.simplify(sum((v.exponent for v in vals), sp.S.Zero))

    def _coefficient(self, indices: tuple[int, ...]) -> sp.Expr:
        vals = [self.tail.get(i) for i in indices]
        counts = Counter(indices)
        multiplicity = sp.factorial(len(indices))
        for value in counts.values():
            multiplicity /= sp.factorial(value)
        return self.taylor(len(indices)) * multiplicity * sp.prod(v.coefficient for v in vals)

    def _push(self, indices: tuple[int, ...]) -> None:
        if not indices or indices in self.seen:
            return
        weight = self._weight(indices)
        if weight is None:
            return
        self.seen.add(indices)
        heapq.heappush(self.heap, (exponent_key(weight), next(self.ticket), indices, weight))

    def _initialize(self) -> None:
        if self.initialized:
            return
        self._push((0,))
        self.initialized = True
        self._update_exhausted()

    def _advance(self, indices: tuple[int, ...]) -> None:
        for pos in range(len(indices) - 1, -1, -1):
            if pos < len(indices) - 1 and indices[pos] == indices[pos + 1]:
                continue
            cand = list(indices)
            cand[pos] += 1
            if pos + 1 < len(cand) and cand[pos] > cand[pos + 1]:
                continue
            self._push(tuple(cand))
        if all(i == 0 for i in indices):
            self._push((0,) * (len(indices) + 1))

    def _update_exhausted(self) -> None:
        self.exhausted = not self.heap and self.tail.exhausted

    def terms_up_to(self, n: int) -> list[LazyTerm]:
        self._initialize()
        while len(self.output) < n and (self.heap or self.pending is not None):
            if self.pending is None:
                _, _, indices, exponent = heapq.heappop(self.heap)
                batch = [indices]
                coefficient = self._coefficient(indices)
                while self.heap:
                    _, _, other, e2 = self.heap[0]
                    if sp.simplify(e2 - exponent) != 0:
                        break
                    heapq.heappop(self.heap)
                    coefficient += self._coefficient(other)
                    batch.append(other)
                self.pending = (exponent, coefficient, batch)
            exponent, coefficient, batch = self.pending
            zero = coefficient == 0
            if len(batch) > 1 and not zero and self.owner._potential_cancellation(coefficient):
                zero = self.owner._zero_or_suspend(
                    coefficient,
                    self.node,
                    "analytic composition must decide cancellation of Taylor contributions",
                )
            for item in batch:
                self._advance(item)
            if not zero:
                self.output.append(LazyTerm(exponent, analytic_powsimp(coefficient)))
            self.pending = None
            self._update_exhausted()
        return self.output[:n]


@dataclass
class _AnalyticState:
    signature: tuple[object, ...]
    constant_term: LazyTerm | None
    frontier: _DynamicAnalyticFrontier
    output: list[LazyTerm] = field(default_factory=list)

    def terms_up_to(self, n: int) -> list[LazyTerm]:
        if n <= 0:
            return []
        if self.constant_term is not None:
            self.frontier.terms_up_to(max(0, n - 1))
            self.output = [self.constant_term, *self.frontier.output[: max(0, n - 1)]]
        else:
            self.frontier.terms_up_to(n)
            self.output = list(self.frontier.output[:n])
        return self.output[:n]


class LazySparseSeries:
    """True demand-driven sparse generalized series in one formal variable."""

    def __init__(
        self,
        expr: sp.Expr,
        z: sp.Symbol,
        context: AsymptoticContext,
        *,
        log_z: sp.Expr | None = None,
        max_depth: int = 80,
        knowledge: AsymptoticKnowledge | None = None,
    ) -> None:
        self.expr = sp.sympify(expr)
        self.z = z
        self.context = context
        self.log_z = None if log_z is None else sp.sympify(log_z)
        self.max_depth = max_depth
        self.knowledge = knowledge or AsymptoticKnowledge()
        self._states: dict[sp.Expr, SparseNodeState] = {}
        self._eval_stack: list[SparseNodeState] = []
        self.obligation: AsymptoticObligation | None = None
        self.resume_count = 0

    def stream(self, expr: sp.Expr | None = None) -> SparseTermStream:
        return SparseTermStream(self, self.expr if expr is None else sp.sympify(expr))

    def continuation(self, n: int) -> SparseContinuation:
        return SparseContinuation(self, max(0, int(n)))

    @property
    def node_states(self) -> tuple[SparseNodeState, ...]:
        return tuple(self._states.values())

    def resume(self, obligation: AsymptoticObligation | None = None) -> None:
        target = obligation or self.obligation
        if target is None:
            return
        key = target.key
        for state in self._states.values():
            if state.obligation is not None and state.obligation.key == key:
                state.status = ContinuationStatus.READY
                state.obligation = None
                state.resumptions += 1
        if self.obligation is not None and self.obligation.key == key:
            self.obligation = None
        self.resume_count += 1

    def terms(self, n: int) -> list[LazyTerm] | None:
        n = int(n)
        if n <= 0:
            return []
        if self.obligation is not None and self.knowledge.contains(self.obligation):
            self.resume(self.obligation)
        value = self._eval(self.expr, n, 0)
        return None if value is None else list(value[:n])

    def _state(self, expr: sp.Expr) -> SparseNodeState:
        expr = sp.sympify(expr)
        if expr not in self._states:
            self._states[expr] = SparseNodeState(expr=expr)
        return self._states[expr]

    def _record_obligation(self, obligation: AsymptoticObligation) -> None:
        if self.obligation is None:
            self.obligation = obligation
        causal = self.obligation
        for state in self._eval_stack:
            state.status = ContinuationStatus.SUSPENDED
            state.obligation = causal

    def _potential_cancellation(self, coefficient: sp.Expr) -> bool:
        coefficient = sp.sympify(coefficient)
        if coefficient == 0:
            return True
        if not coefficient.is_Add:
            return False
        signs = {bool(term.could_extract_minus_sign()) for term in coefficient.args}
        return len(signs) > 1

    def _zero_or_suspend(self, coefficient: sp.Expr, node: sp.Expr, reason: str) -> bool:
        coefficient = analytic_powsimp(coefficient)
        if coefficient == 0:
            return True
        obligation = ZeroTestObligation(node, coefficient, reason)
        known = self.knowledge.get(obligation, None)
        if known is None:
            known = self.context.is_zero(coefficient)
            if known is not None:
                self.knowledge.set(obligation, known)
        if known is None:
            self._record_obligation(obligation)
            raise _Suspend
        return bool(known)

    def _eval(self, expr: sp.Expr, n: int, depth: int) -> tuple[LazyTerm, ...] | None:
        expr = sp.sympify(expr)
        state = self._state(expr)
        if depth > self.max_depth:
            obligation = DepthLimitObligation(expr)
            self._record_obligation(obligation)
            state.status = ContinuationStatus.SUSPENDED
            state.obligation = obligation
            return None
        if state.status is ContinuationStatus.SUSPENDED and state.obligation is not None:
            if self.knowledge.contains(state.obligation):
                self.resume(state.obligation)
            else:
                self._record_obligation(state.obligation)
                return None
        if len(state.result) >= n or state.exhausted:
            return state.result[:n]

        state.status = ContinuationStatus.RUNNING
        state.requested = max(state.requested, n)
        if not state.payload.get("_started"):
            state.evaluations += 1
            state.payload["_started"] = True
        self._eval_stack.append(state)
        try:
            result = self._produce(expr, n, depth, state)
        except _Suspend:
            state.status = ContinuationStatus.SUSPENDED
            state.obligation = self.obligation
            return None
        finally:
            self._eval_stack.pop()
        if result is None:
            state.status = ContinuationStatus.READY
            return None
        state.result = tuple(result)
        state.status = ContinuationStatus.DONE
        state.obligation = None
        return state.result[:n]

    def _produce(
        self, expr: sp.Expr, n: int, depth: int, state: SparseNodeState
    ) -> list[LazyTerm] | None:
        z = self.z
        if not expr.has(z):
            state.exhausted = True
            return [] if expr == 0 else [LazyTerm(sp.S.Zero, expr)]
        if expr == z:
            state.exhausted = True
            return [LazyTerm(sp.S.One, sp.S.One)]
        if expr.is_Add:
            frontier = state.payload.get("add")
            if not isinstance(frontier, _PersistentAddFrontier):
                frontier = _PersistentAddFrontier(self, expr.args, depth + 1, expr)
                state.payload["add"] = frontier
            result = frontier.terms_up_to(n)
            state.exhausted = frontier.exhausted
            return result
        if expr.is_Mul:
            return self._mul(expr.args, n, depth + 1, state)
        if expr.is_Pow:
            return self._pow(expr, n, depth + 1, state)
        if expr.func is sp.exp:
            return self._exp_expr(expr, n, depth + 1, state)
        if expr.func is sp.log:
            return self._log_expr(expr, n, depth + 1, state)
        if expr.func in _ANALYTIC_UNARY_FUNCS and len(expr.args) == 1:
            return self._generic_analytic_expr(expr, n, depth + 1, state)
        self._record_obligation(UnsupportedNodeObligation(expr))
        raise _Suspend

    def _mul(
        self, args: tuple[sp.Expr, ...], n: int, depth: int, state: SparseNodeState
    ) -> list[LazyTerm]:
        if not args:
            state.exhausted = True
            return [LazyTerm(0, 1)]
        source = _NodeSource(self, args[0], depth)
        if len(args) == 1:
            value = self._eval(args[0], n, depth)
            state.exhausted = self._state(args[0]).exhausted
            return list(value or ())
        for stage, arg in enumerate(args[1:], 1):
            key = f"product:{stage}"
            frontier = state.payload.get(key)
            right = _NodeSource(self, arg, depth)
            if not isinstance(frontier, _PersistentProductFrontier):
                frontier = _PersistentProductFrontier(self, source, right, state.expr)
                state.payload[key] = frontier
            source = _ProductSource(frontier)
        result = []
        for i in range(n):
            term = source.get(i)
            if term is None:
                break
            result.append(term)
        state.exhausted = source.exhausted
        return result

    def _pow(
        self, expr: sp.Expr, n: int, depth: int, state: SparseNodeState
    ) -> list[LazyTerm] | None:
        base, exponent = expr.as_base_exp()
        if base == self.z and not exponent.has(self.z):
            state.exhausted = True
            return [LazyTerm(exponent, sp.S.One)]
        if exponent.is_Integer and exponent >= 0:
            if exponent == 0:
                state.exhausted = True
                return [LazyTerm(0, 1)]
            # Preserve an unevaluated multiplication node so integer powers use
            # the exact same stream product machinery as ordinary products.
            factors = tuple(base for _ in range(int(exponent)))
            pseudo = sp.Mul(*factors, evaluate=False)
            pstate = self._state(pseudo)
            result = self._mul(factors, n, depth, pstate)
            state.payload["integer-power-state"] = pstate
            state.exhausted = pstate.exhausted
            return result
        if not exponent.has(self.z):
            return self._constant_power_expr(base, exponent, n, depth, state)
        rewritten = sp.exp(exponent * sp.log(base, evaluate=False), evaluate=False)
        value = self._eval(rewritten, n, depth)
        state.exhausted = self._state(rewritten).exhausted
        return None if value is None else list(value)

    def _source_center_tail(self, inner: sp.Expr, depth: int, node: sp.Expr):
        src = _NodeSource(self, inner, depth)
        first = src.get(0)
        if first is None:
            return sp.S.Zero, _MappedSource(src, lambda t: t, 0), src
        if sp.simplify(first.exponent) == 0:
            constant = first.coefficient
            tail = _MappedSource(src, lambda t: t if t.exponent.is_positive is True else None, 1)
            return constant, tail, src
        if first.exponent.is_positive is True:
            return (
                sp.S.Zero,
                _MappedSource(src, lambda t: t if t.exponent.is_positive is True else None, 0),
                src,
            )
        return None, None, src

    def _analytic_state(
        self, state: SparseNodeState, key: str, constant: sp.Expr, tail, derivative, node
    ) -> _AnalyticState:
        signature = (sp.srepr(constant), id(tail))
        stored = state.payload.get(key)
        if isinstance(stored, _AnalyticState):
            return stored
        c0 = analytic_powsimp(derivative(0, constant))
        constant_term = None
        if not self._zero_or_suspend(
            c0, node, "analytic constant term requires zero classification"
        ):
            constant_term = LazyTerm(sp.S.Zero, c0)

        def taylor(p: int) -> sp.Expr:
            return derivative(p, constant) / sp.factorial(p)

        stored = _AnalyticState(
            signature, constant_term, _DynamicAnalyticFrontier(self, tail, taylor, node)
        )
        state.payload[key] = stored
        return stored

    def _generic_analytic_expr(self, expr: sp.Expr, n: int, depth: int, state: SparseNodeState):
        constant, tail, _src = self._source_center_tail(expr.args[0], depth, expr)
        if constant is None:
            self._record_obligation(
                NonAnalyticObligation(expr, "analytic composition requires a finite regular center")
            )
            raise _Suspend
        u = sp.Dummy("u")
        template = expr.func(u)
        derivs = {}

        def derivative(p: int, c: sp.Expr) -> sp.Expr:
            if p not in derivs:
                derivs[p] = template if p == 0 else sp.diff(template, u, p)
            value = analytic_powsimp(derivs[p].subs(u, c))
            if value.has(sp.zoo, sp.nan) or value in (sp.oo, -sp.oo):
                self._record_obligation(
                    NonAnalyticObligation(expr, f"{expr.func} is singular at expansion center {c}")
                )
                raise _Suspend
            return value

        stored = self._analytic_state(
            state, f"analytic:generic:{expr.func}", constant, tail, derivative, expr
        )
        result = stored.terms_up_to(n)
        state.exhausted = stored.frontier.exhausted and (
            stored.constant_term is None or len(result) >= 1
        )
        return result

    def _exp_expr(self, expr: sp.Expr, n: int, depth: int, state: SparseNodeState):
        constant, tail, src = self._source_center_tail(expr.args[0], depth, expr)
        if constant is None:
            # Gather the complete divergent prefix available from this frontier. Since
            # child streams are exact, this is not an oversampling heuristic.
            negatives = []
            i = 0
            while True:
                term = src.get(i)
                if term is None:
                    break
                if term.exponent.is_negative is True:
                    negatives.append(term)
                    i += 1
                    continue
                break
            divergent = sp.Add(*[t.coefficient * self.z**t.exponent for t in negatives])
            if divergent != 0:
                self._record_obligation(
                    ExponentialScaleObligation(expr, expr.args[0], analytic_powsimp(divergent))
                )
                raise _Suspend
            return None
        stored = self._analytic_state(
            state, "analytic:exp", constant, tail, lambda _p, c: sp.exp(c), expr
        )
        result = stored.terms_up_to(n)
        state.exhausted = stored.frontier.exhausted
        return result

    def _log_expr(self, expr: sp.Expr, n: int, depth: int, state: SparseNodeState):
        src = _NodeSource(self, expr.args[0], depth)
        lead = src.get(0)
        if lead is None:
            self._record_obligation(
                NonAnalyticObligation(expr, "logarithm has no nonzero leading term")
            )
            raise _Suspend
        lead_zero = self._zero_or_suspend(
            lead.coefficient, expr, "logarithm requires a nonzero leading coefficient"
        )
        if lead_zero:
            self._record_obligation(
                NonAnalyticObligation(expr, "logarithm leading coefficient is zero")
            )
            raise _Suspend
        r = sp.simplify(lead.exponent)
        a = analytic_powsimp(lead.coefficient)
        if r == 0:
            tail = _MappedSource(src, lambda t: t if t.exponent.is_positive is True else None, 1)

            def derivative(p: int, c: sp.Expr) -> sp.Expr:
                return sp.log(c) if p == 0 else (-1) ** (p - 1) * sp.factorial(p - 1) / c**p

            stored = self._analytic_state(state, "analytic:log-center", a, tail, derivative, expr)
            result = stored.terms_up_to(n)
            state.exhausted = stored.frontier.exhausted
            return result
        if self.log_z is None or self.log_z.has(self.z):
            self._record_obligation(LogarithmicScaleObligation(expr, r))
            raise _Suspend
        tail = _MappedSource(
            src,
            lambda t: (
                LazyTerm(sp.simplify(t.exponent - r), sp.simplify(t.coefficient / a))
                if sp.simplify(t.exponent - r).is_positive is True
                else None
            ),
            1,
        )
        key = "analytic:log-tail"
        stored = state.payload.get(key)
        if not isinstance(stored, _AnalyticState):
            c0 = LazyTerm(sp.S.Zero, sp.log(a) + r * self.log_z)

            def taylor(p: int) -> sp.Expr:
                return (-1) ** (p - 1) / sp.Integer(p)

            frontier = _DynamicAnalyticFrontier(self, tail, taylor, expr)
            stored = _AnalyticState((sp.srepr(a), sp.srepr(r)), c0, frontier)
            state.payload[key] = stored
        result = stored.terms_up_to(n)
        state.exhausted = stored.frontier.exhausted
        return result

    def _constant_power_expr(
        self, base: sp.Expr, exponent: sp.Expr, n: int, depth: int, state: SparseNodeState
    ):
        src = _NodeSource(self, base, depth)
        lead = src.get(0)
        if lead is None:
            state.exhausted = True
            return []
        if self._zero_or_suspend(
            lead.coefficient, state.expr, "power requires a nonzero leading coefficient"
        ):
            return None
        r = sp.simplify(lead.exponent)
        a = analytic_powsimp(lead.coefficient)
        tail = _MappedSource(
            src,
            lambda t: (
                LazyTerm(sp.simplify(t.exponent - r), sp.simplify(t.coefficient / a))
                if sp.simplify(t.exponent - r).is_positive is True
                else None
            ),
            1,
        )
        key = f"analytic:power:{sp.srepr(exponent)}"
        stored = state.payload.get(key)
        if not isinstance(stored, _AnalyticState):
            constant = LazyTerm(sp.simplify(r * exponent), analytic_powsimp(a**exponent))

            def taylor(p: int) -> sp.Expr:
                if p == 0:
                    return sp.S.One
                return sp.prod(exponent - k for k in range(p)) / sp.factorial(p)

            frontier = _DynamicAnalyticFrontier(self, tail, taylor, state.expr)

            # correction exponents need the leading shift and coefficient.
            class ShiftedFrontier:
                def __init__(self, raw):
                    self.raw = raw
                    self.output = []

                @property
                def exhausted(self):
                    return self.raw.exhausted

                def terms_up_to(self, m):
                    raw = self.raw.terms_up_to(m)
                    self.output = [
                        LazyTerm(
                            sp.simplify(r * exponent + t.exponent),
                            analytic_powsimp(a**exponent * t.coefficient),
                        )
                        for t in raw
                    ]
                    return self.output[:m]

            shifted = ShiftedFrontier(frontier)
            stored = _AnalyticState(
                (sp.srepr(a), sp.srepr(r), sp.srepr(exponent)), constant, shifted
            )  # type: ignore[arg-type]
            state.payload[key] = stored
        result = stored.terms_up_to(n)
        state.exhausted = stored.frontier.exhausted
        return result
