import importlib
from types import ModuleType

import asymptotic

SPECIALIST_EXPORTS = [
    ("reversion", "series_reversion"),
    ("algebra", "AsymptoticAlgebra"),
    ("algebra", "AsymptoticElement"),
    ("context", "AsymptoticGrowthComparison"),
    ("regime_selection", "AsymptoticRegime"),
    ("relations", "RelationResult"),
    ("stratified_expansion", "CertifiedPowerExpansion"),
    ("complex_domains", "ComplexDomainCertificate"),
    ("perturbation_problem", "ConvergenceDiagnostics"),
    ("discrete_limits", "DiscreteLimitResult"),
    ("local_expansion", "ExpansionCertificate"),
    ("uniform_special_expansions", "ExponentialRemainderCertificate"),
    ("hyperasymptotics", "ExponentialScale"),
    ("hyperasymptotics", "HyperasymptoticExpansion"),
    ("multivariate_laplace", "LaplaceRatioResult"),
    ("lindstedt", "LindstedtPoincareResult"),
    ("multivariate_laplace", "LocalGaussianForm"),
    ("mellin", "MellinResult"),
    ("perturbation_problem", "MethodRecommendation"),
    ("multivariate_laplace", "MultivariateLaplaceResult"),
    ("nested", "NestedExpansion"),
    ("variation_bounds", "OlverErrorControl"),
    ("perturbation_problem", "PerturbationCondition"),
    ("perturbation", "PerturbationHierarchy"),
    ("perturbation", "PerturbationOrder"),
    ("perturbation_problem", "PerturbationProblem"),
    ("perturbation_problem", "PerturbationResult"),
    ("regime_selection", "RegimeCertificate"),
    ("regime_selection", "RegimeGeometry"),
    ("regular_perturbation", "RegularPerturbationResult"),
    ("uniform_special_expansions", "RemainderBound"),
    ("public_result", "ResultExplanation"),
    ("saddle_geometry", "SaddleGeometryCertificate"),
    ("local_expansion", "SectorCertificate"),
    ("uniform_special_expansions", "StokesCertificate"),
    ("stokes_geometry", "StokesGeometryCertificate"),
    ("hyperasymptotics", "StokesTransition"),
    ("stratified_expansion", "StratifiedExpansion"),
    ("special_functions", "StruveH"),
    ("special_functions", "StruveL"),
    ("hyperasymptotics", "TerminantLevel"),
    ("variation_bounds", "TotalVariation"),
    ("turning_point_families", "TurningPointAdapter"),
    ("uniform_special_expansions", "TurningPointCertificate"),
    ("turning_point_families", "TurningPointFamily"),
    ("uniform_integration", "UniformCompositeExpansion"),
    ("uniform_special_expansions", "UniformExpansion"),
    ("uniform_zeros", "UniformZeroApproximation"),
    ("perturbation_problem", "ValidationReport"),
    ("variation_bounds", "VariationCertificate"),
    ("uniform_special_expansions", "airy_ai_exponentially_improved"),
    ("uniform_special_expansions", "airy_stokes_expansion"),
    ("olver_coefficients", "airy_u"),
    ("probability", "airy_uniform_saddle_asymptotic"),
    ("olver_coefficients", "airy_v"),
    ("saddle_geometry", "analyze_exponential_integral"),
    ("saddle_geometry", "analyze_saddle_geometry"),
    ("stokes_geometry", "analyze_stokes_geometry"),
    ("turning_point_families", "associated_legendre_large_degree"),
    ("turning_point_families", "associated_legendre_turning_point"),
    ("complex_domains", "bessel_complex_domain"),
    ("uniform_special_expansions", "bessel_j_exponentially_improved"),
    ("uniform_special_expansions", "bessel_j_large_order"),
    ("uniform_special_expansions", "bessel_j_prime_large_order"),
    ("uniform_special_expansions", "bessel_j_transition"),
    ("uniform_special_expansions", "bessel_y_exponentially_improved"),
    ("uniform_special_expansions", "bessel_y_large_order"),
    ("uniform_special_expansions", "bessel_y_prime_large_order"),
    ("uniform_zeros", "bessel_zero_large_order"),
    ("probability", "coalescing_saddle_asymptotic"),
    ("general_ops", "compose_transseries"),
    ("olver_coefficients", "debye_u"),
    ("olver_coefficients", "debye_v"),
    ("variation_bounds", "debye_variation"),
    ("dominant", "dominant_balance_candidates"),
    ("uniform_special_expansions", "hankel_exponentially_improved"),
    ("uniform_special_expansions", "hankel_large_order"),
    ("uniform_special_expansions", "hankel_prime_large_order"),
    ("probability", "laplace_asymptotic_integral"),
    ("multivariate_laplace", "laplace_ratio_asymptotic"),
    ("hyperasymptotics", "least_term_index"),
    ("multivariate_laplace", "local_gaussian_form"),
    ("multivariate_laplace", "log_laplace_asymptotic"),
    ("variation_bounds", "materialize_turning_point_variation"),
    ("complex_domains", "modified_bessel_complex_domain"),
    ("uniform_special_expansions", "modified_bessel_i_large_order"),
    ("uniform_special_expansions", "modified_bessel_i_prime_large_order"),
    ("uniform_special_expansions", "modified_bessel_k_large_order"),
    ("uniform_special_expansions", "modified_bessel_k_prime_large_order"),
    ("mrv", "mrv_decomposition"),
    ("multivariate", "multivariate_dominant_balance_candidates"),
    ("multivariate_implicit", "multivariate_implicit"),
    ("multivariate_laplace", "multivariate_laplace_integral"),
    ("olver_coefficients", "olver_coefficient"),
    ("olver_coefficients", "olver_coefficient_block"),
    ("variation_bounds", "olver_error_control"),
    ("olver_coefficients", "olver_turning_table"),
    ("olver_coefficients", "olver_zeta"),
    ("uniform_special_expansions", "optimally_truncated_airy_ai"),
    ("turning_point_families", "parabolic_cylinder_turning_point"),
    ("perturbation", "perturbation_hierarchy"),
    ("variation_bounds", "polynomial_segment_variation"),
    ("uniform_special_expansions", "rescaled_terminant"),
    ("regime_selection", "select_asymptotic_regime"),
    ("stokes_geometry", "select_stokes_regime"),
    ("hyperasymptotics", "stokes_transition"),
    ("hyperasymptotics", "terminant"),
    ("hyperasymptotics", "terminant_reexpand"),
    ("transseries", "transseries_from_expression"),
    ("variation_bounds", "turning_point_variation"),
    ("uniform_integration", "uniform_atom_expansion"),
    ("uniform_integration", "uniform_composite_expansion"),
    ("uniform_integration", "uniform_limit_value"),
    ("uniform_zeros", "uniform_zero_approximation"),
    ("turning_point_families", "whittaker_m_large_kappa"),
    ("turning_point_families", "whittaker_turning_point"),
]
EXPERT_NAMES = [
    "AsymptoticAlgebra",
    "AsymptoticElement",
    "AsymptoticGrowthComparison",
    "AsymptoticRegime",
    "RelationResult",
    "CertifiedPowerExpansion",
    "ComplexDomainCertificate",
    "ConvergenceDiagnostics",
    "DiscreteLimitResult",
    "ExpansionCertificate",
    "ExponentialRemainderCertificate",
    "ExponentialScale",
    "HyperasymptoticExpansion",
    "LaplaceRatioResult",
    "LindstedtPoincareResult",
    "LocalGaussianForm",
    "MRVTiming",
    "MellinResult",
    "MethodRecommendation",
    "MultivariateLaplaceResult",
    "NestedExpansion",
    "OlverErrorControl",
    "PerturbationCondition",
    "PerturbationHierarchy",
    "PerturbationOrder",
    "PerturbationProblem",
    "PerturbationResult",
    "RegimeCertificate",
    "RegimeGeometry",
    "RegularPerturbationResult",
    "RemainderBound",
    "ResultExplanation",
    "SaddleGeometryCertificate",
    "SectorCertificate",
    "StokesCertificate",
    "StokesGeometryCertificate",
    "StokesTransition",
    "StratifiedExpansion",
    "StruveH",
    "StruveL",
    "TerminantLevel",
    "TotalVariation",
    "TurningPointAdapter",
    "TurningPointCertificate",
    "TurningPointFamily",
    "UniformCompositeExpansion",
    "UniformExpansion",
    "UniformZeroApproximation",
    "ValidationReport",
    "VariationCertificate",
    "airy_ai_exponentially_improved",
    "airy_stokes_expansion",
    "airy_u",
    "airy_uniform_saddle_asymptotic",
    "airy_v",
    "analyze_exponential_integral",
    "analyze_saddle_geometry",
    "analyze_stokes_geometry",
    "associated_legendre_large_degree",
    "associated_legendre_turning_point",
    "asymptotic_integrate",
    "bessel_complex_domain",
    "bessel_j_exponentially_improved",
    "bessel_j_large_order",
    "bessel_j_prime_large_order",
    "bessel_j_transition",
    "bessel_y_exponentially_improved",
    "bessel_y_large_order",
    "bessel_y_prime_large_order",
    "bessel_zero_large_order",
    "coalescing_saddle_asymptotic",
    "compose_transseries",
    "debye_u",
    "debye_v",
    "debye_variation",
    "dominant_balance_candidates",
    "hankel_exponentially_improved",
    "hankel_large_order",
    "hankel_prime_large_order",
    "laplace_asymptotic_integral",
    "laplace_ratio_asymptotic",
    "least_term_index",
    "local_gaussian_form",
    "log_laplace_asymptotic",
    "materialize_turning_point_variation",
    "modified_bessel_complex_domain",
    "modified_bessel_i_large_order",
    "modified_bessel_i_prime_large_order",
    "modified_bessel_k_large_order",
    "modified_bessel_k_prime_large_order",
    "mrv_decomposition",
    "mrv_hardy_timing",
    "multivariate_dominant_balance_candidates",
    "multivariate_implicit",
    "multivariate_laplace_integral",
    "olver_coefficient",
    "olver_coefficient_block",
    "olver_error_control",
    "olver_turning_table",
    "olver_zeta",
    "optimally_truncated_airy_ai",
    "parabolic_cylinder_turning_point",
    "perturbation_hierarchy",
    "polynomial_segment_variation",
    "rescaled_terminant",
    "select_asymptotic_regime",
    "select_stokes_regime",
    "stokes_transition",
    "terminant",
    "terminant_reexpand",
    "transseries_from_expression",
    "turning_point_variation",
    "uniform_atom_expansion",
    "uniform_composite_expansion",
    "uniform_limit_value",
    "uniform_zero_approximation",
    "whittaker_m_large_kappa",
    "whittaker_turning_point",
]


def test_expert_names_are_not_root_exports():
    # Importing a child module sets a normal package attribute with its name.
    # The public API excludes specialist functions and classes, not modules.
    module = importlib.import_module("asymptotic.multivariate_implicit")
    assert asymptotic.multivariate_implicit is module
    assert set(EXPERT_NAMES).isdisjoint(asymptotic.__all__)
    assert all(
        isinstance(getattr(asymptotic, name, None), (ModuleType, type(None)))
        for name in EXPERT_NAMES
    )


def test_specialist_api_remains_importable_from_canonical_modules():
    for module_name, name in SPECIALIST_EXPORTS:
        assert hasattr(importlib.import_module(f"asymptotic.{module_name}"), name)


def test_series_reversion_is_specialist_only():
    assert "series_reversion" not in asymptotic.__dict__
    module = importlib.import_module("asymptotic.reversion")
    assert callable(module.series_reversion)
